### ISSUE TITLE
Error in importing mapFunctions

### ISSUE THREAD

**Issue by markyenatu** [jddingemanse/pycamtET#1]
In some computers importing mapFunctions from pycamtET returns an error as "ImportError: cannot import name '_metercrs' from 'pycamtET.supportMap'". But in some, it imports properly following the same procedure in installing geopandas as well as pycamtET. Have you encountered this? any solution and also what is the reason behind?

Best

**Comment by jddingemanse** [comment]
That error has to do with the fact that something in the Geopandas installation is not working properly. Versions 0.0.4 of pycamtET and 0.0.3 of pycamtETinterface should have solved this issue. To install / update to these versions, just run the installation again (```pip install git+https://github.com/jddingemanse/pycamtET```) and ```pip install git+https://github.com/jddingemanse/pycamtETinterface.git```).

In earlier versions, during initialization (at the moment of ```import pycamtET```) it was checked whether shapefiles are present and Geopandas is installed - if that was not the case, you got a friendly warning. This check has now been extended to also if Geopandas is installed but shapefiles cannot be loaded for some reason. In other words, instead of an error, from version 0.0.4 you should now get a warning, .mapFunctions will not work, but the rest you can use. (With pycamtETinterface version 0.0.3 in the Jupyter Notebook, the tab for mapping in the interface should simply not load)

The underlying issue is a problem with the Geopandas package. You can check whether you geopandas installation works properly by trying to load a shapefile with it.
```
import geopandas as gpd
gpd.read_file('pathToShapefile')
```
I expect that the PCs at which you encountered your mentioned error, will also result in an error with reading shapefiles with geopandas. Of that issue, I do not know yet know how to solve it. It has to do with a problem in the package fiona, and specifically seems to go wrong for PCs with a recent geopandas installation.

Please let me know whether an update to the newest pycamtET at least solves the error you encountered (but, still you will not be able to use .mapFunctions, because that depends on Geopandas working properly).
